/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as authenticatedImport } from './routes/__authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsIdImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedSettingsUpdateUserIdImport } from './routes/_authenticated/settings/update/$userId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedRoute = authenticatedImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/_authenticated/settings/',
    path: '/settings/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthenticatedProjectsIndexRoute = AuthenticatedProjectsIndexImport.update(
  {
    id: '/_authenticated/projects/',
    path: '/projects/',
    getParentRoute: () => rootRoute,
  } as any,
)

const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdImport.update({
  id: '/_authenticated/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsUpdateUserIdRoute =
  AuthenticatedSettingsUpdateUserIdImport.update({
    id: '/_authenticated/settings/update/$userId',
    path: '/settings/update/$userId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings/update/$userId': {
      id: '/_authenticated/settings/update/$userId'
      path: '/settings/update/$userId'
      fullPath: '/settings/update/$userId'
      preLoaderRoute: typeof AuthenticatedSettingsUpdateUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authenticatedRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/update/$userId': typeof AuthenticatedSettingsUpdateUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authenticatedRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/update/$userId': typeof AuthenticatedSettingsUpdateUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__authenticated': typeof authenticatedRoute
  '/about': typeof AboutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/update/$userId': typeof AuthenticatedSettingsUpdateUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/dashboard'
    | '/projects/$id'
    | '/projects'
    | '/settings'
    | '/settings/update/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/dashboard'
    | '/projects/$id'
    | '/projects'
    | '/settings'
    | '/settings/update/$userId'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/about'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/update/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRoute: typeof authenticatedRoute
  AboutRoute: typeof AboutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsUpdateUserIdRoute: typeof AuthenticatedSettingsUpdateUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRoute: authenticatedRoute,
  AboutRoute: AboutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsUpdateUserIdRoute:
    AuthenticatedSettingsUpdateUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__authenticated",
        "/about",
        "/_authenticated/dashboard",
        "/_authenticated/projects/$id",
        "/_authenticated/projects/",
        "/_authenticated/settings/",
        "/_authenticated/settings/update/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__authenticated": {
      "filePath": "__authenticated.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx"
    },
    "/_authenticated/projects/$id": {
      "filePath": "_authenticated/projects/$id.tsx"
    },
    "/_authenticated/projects/": {
      "filePath": "_authenticated/projects/index.tsx"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx"
    },
    "/_authenticated/settings/update/$userId": {
      "filePath": "_authenticated/settings/update/$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
